# Generated by Django 5.1.4 on 2024-12-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puede_tener_promociones', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(max_length=300)),
                ('descuento', models.IntegerField()),
                ('fechaPromocion', models.DateField()),
                ('fechaFinPromocion', models.DateField()),
                ('productos', models.ManyToManyField(related_name='promociones_productos', to='apicacionCRUD.producto')),
                ('usuarios', models.ManyToManyField(related_name='promociones_usuarios', to='apicacionCRUD.usuario')),
            ],
        ),
    ]
